#ifndef UNTITLED_SETTINGS_H
#define UNTITLED_SETTINGS_H

// Text colors in ANSI escape codes
#define COLOR_BLACK      "\033[0;30m"
#define COLOR_RED        "\033[0;31m"
#define COLOR_GREEN      "\033[0;32m"
#define COLOR_YELLOW     "\033[0;33m"
#define COLOR_BLUE       "\033[0;34m"
#define COLOR_MAGENTA    "\033[0;35m"
#define COLOR_CYAN       "\033[0;36m"
#define COLOR_GRAY       "\033[0;37m"
#define COLOR_DARK_GRAY  "\033[1;30m"
#define COLOR_LIGHT_RED  "\033[1;31m"
#define COLOR_LIGHT_GREEN "\033[1;32m"
#define COLOR_LIGHT_YELLOW "\033[1;33m"
#define COLOR_LIGHT_BLUE "\033[1;34m"
#define COLOR_LIGHT_MAGENTA "\033[1;35m"
#define COLOR_LIGHT_CYAN "\033[1;36m"
#define COLOR_WHITE      "\033[1;37m"
#define COLOR_RESET      "\033[0m"

// ---ANIMALS---
// Czlowiek
#define CZLOWIEK_SKIN COLOR_BLUE "C" COLOR_RESET
#define CZLOWIEK_STRENGTH 5
#define CZLOWIEK_INITIATIVE 4
#define CZLOWIEK_NAME COLOR_BLUE "Czlowiek" COLOR_RESET
#define CZLOWIEK_NORMAL_NAME "Czlowiek"

// Wilk
#define WILK_SKIN COLOR_GRAY "W" COLOR_RESET
#define WILK_STRENGTH 9
#define WILK_INITIATIVE 5
#define WILK_NAME COLOR_GRAY "Wilk" COLOR_RESET
#define WILK_NORMAL_NAME "Wilk"


// Owca
#define OWCA_SKIN COLOR_WHITE "O" COLOR_RESET
#define OWCA_STRENGTH 4
#define OWCA_INITIATIVE 4
#define OWCA_NAME COLOR_WHITE "Owca" COLOR_RESET
#define OWCA_NORMAL_NAME "Owca"

// Lis
#define LIS_SKIN COLOR_RED "L" COLOR_RESET
#define LIS_STRENGTH 3
#define LIS_INITIATIVE 7
#define LIS_NAME COLOR_RED "Lis" COLOR_RESET
#define LIS_NORMAL_NAME "Lis"

// Zolw
#define ZOLW_SKIN COLOR_GREEN "Z" COLOR_RESET
#define ZOLW_STRENGTH 2
#define ZOLW_INITIATIVE 1
#define ZOLW_NAME COLOR_GREEN "Zolw" COLOR_RESET
#define ZOLW_NORMAL_NAME "Zolw"

// Antylopa
#define ANTYLOPA_SKIN COLOR_YELLOW "A" COLOR_RESET
#define ANTYLOPA_STRENGTH 4
#define ANTYLOPA_INITIATIVE 4
#define ANTYLOPA_NAME COLOR_YELLOW "Antylopa" COLOR_RESET
#define ANTYLOPA_NORMAL_NAME "Antylopa"

// ---PLANTS---
// Trawa
#define TRAWA_SKIN COLOR_LIGHT_GREEN "T" COLOR_RESET
#define TRAWA_STRENGTH 0
#define TRAWA_INITIATIVE 0
#define TRAWA_NAME COLOR_LIGHT_GREEN "Trawa" COLOR_RESET
#define TRAWA_NORMAL_NAME "Trawa"

// Mlecz
#define MLECZ_SKIN COLOR_LIGHT_YELLOW "M" COLOR_RESET
#define MLECZ_STRENGTH 0
#define MLECZ_INITIATIVE 0
#define MLECZ_NAME COLOR_LIGHT_YELLOW "Mlecz" COLOR_RESET
#define MLECZ_NORMAL_NAME "Mlecz"

// Guarana
#define GUARANA_SKIN COLOR_LIGHT_RED "G" COLOR_RESET
#define GUARANA_STRENGTH 0
#define GUARANA_INITIATIVE 0
#define GUARANA_NAME COLOR_LIGHT_RED "Guarana" COLOR_RESET
#define GUARANA_NORMAL_NAME "Guarana"

// Jagody
#define JAGODY_SKIN COLOR_RED "J" COLOR_RESET
#define JAGODY_STRENGTH 99
#define JAGODY_INITIATIVE 0
#define JAGODY_NAME COLOR_RED "Jagody" COLOR_RESET
#define JAGODY_NORMAL_NAME "Jagody"


// Barszcz
#define BARSZCZ_SKIN COLOR_LIGHT_BLUE "B" COLOR_RESET
#define BARSZCZ_STRENGTH 10
#define BARSZCZ_INITIATIVE 0
#define BARSZCZ_NAME COLOR_LIGHT_BLUE "Barszcz" COLOR_RESET
#define BARSZCZ_NORMAL_NAME "Barszcz"

#endif //UNTITLED_SETTINGS_H